version: '3.7'

services:
  confluence:
    image: atlassian/confluence  # Using the general Confluence image
    restart: always
    ports:
      - "8090:8090"  # Confluence port set to 9999
      - "8091:8091"  # Confluence port set to 9999


  db:
    image: postgres:13  # Using PostgreSQL image
    restart: always
    environment:
      - POSTGRES_DB=confluence
      - POSTGRES_USER=confluence_user
      - POSTGRES_PASSWORD=password  # Database password

# No volumes defined
